config/routes.rb
Rails.application.routes.draw do
  # get 'articles/index'
  # post '/articles', to: 'articles#create'
  # get '/articles', to: 'articles#index'
  # get '/articles/new', to: 'articles#new', as: :new_article
  # get '/articles/:id', to: 'articles#show', as: :article
  # get '/articles/:id/edit', to: 'articles#edit', as: :edit_article
  # patch '/articles/:id', to: 'articles#update'
  # delete '/articles/:id', to: 'articles#destroy'

  root to: 'articles#index'

  resources :articles do
    resources :comments, shallow: true #only: [:new, :create, :index]
  end
  #resources :comments, only: [:edit, :update, :destroy, :show]
  get 'users/signup', to: 'users#new'
  resources :users, except: :new

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  MINIMUM_PASSWORD_LENGTH = 5

  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true, length: { minimum: MINIMUM_PASSWORD_LENGTH }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # include Clearance::User

  MAXIMUM_NAME_LENGTH = 255
  MAXIMUM_EMAIL_LENGTH = 50
  MINIMUM_PASSWORD_LENGTH = 6
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  has_secure_password
  #dava attr_accessor :password , :password_confirmation argumenti
  # kolona password_digest treba
  #dava metod authenticate, za proverka na passwordot koa ke go vnesuva korisnik

  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy

  before_save :email_to_downcase

  validates :name, presence: true, length: { maximum: MAXIMUM_NAME_LENGTH }
  validates :email, presence: true, length: { maximum: MAXIMUM_EMAIL_LENGTH },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: true }
  validates :password, presence: true, length: { minimum: MINIMUM_PASSWORD_LENGTH }

  private

  def email_to_downcase
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # include Clearance::Controller
  include SessionsHelper

  before_action :require_login

  private

  def require_login
    unless logged_in?
      flash[:danger] = 'Please sign in to continue.'
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :require_login, only: [:index, :show]
  before_action :find_article, except: [:index, :new, :create]
  before_action :same_user, only: [:edit, :update]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    # binding.pry
    # render plain: params[:article].inspect
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    if valid_user?(@article.user)
     @article.destroy
     redirect_to articles_path
    else
      session_notice('danger', 'Wrong user!')
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :body)
  end

  def find_article
    @article = Article.find(params[:id])
  end

  def same_user
    log_in_as?(@article.user)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_comment, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]

  def new
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build
  end

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = @comment.article
  end

  def update
    @article = @comment.article

    if @comment.update(comment_params)
    redirect_to @article
    else
    render :edit
    end
  end

  def destroy
    article = @comment.article
    if  valid_user?(article.user)
      @comment.destroy
      redirect_to @comment.article
     else
      session_notice('danger', 'Wrong user!')
     end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def find_comment
    @comment = Comment.find(params[:id])
  end

  def correct_user
    log_in_as?(@comment.user)

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  
  def new
    session_notice('warning', 'Already logged in!') if logged_in?
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid combination of email or password'
      render :new
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  
  def new
    if logged_in?
      session_notice('warning', 'Already logged in!')
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
     log_in(@user)
     redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def session_notice(type, message)
    flash[type.to_sym] = message
    redirect_to root_path
  end

  def valid_user?(other_user)
    current_user == other_user
  end

  def log_in_as?(user)
    unless valid_user?(user)
      flash[:danger] = 'Wrong user!'
      redirect_to root_path and return
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<div class="column is-6 is-offset-3">
  <div class="card">
    <%# <% unless local_assigns[:show] %>
      <header class="card-header">
        <p class="card-header-title">
          <%= article.title %>
        </p>
      </header>
    <%# <% end %>
    <div class="card-content">
      <div class="content">
        <p><%= article.body %></p>
      </div>
    </div>

    <footer class="card-footer">
      <% if local_assigns[:show] %>
        <%= link_to "Back", root_path, class: "card-footer-item" %>
      <% else %>
        <%= link_to "Show", article_path(article), class: "card-footer-item" %>
      <% end %>
      <% if logged_in? && valid_user?(article.user) %>
        <%= link_to "Edit", edit_article_path(article), class: "card-footer-item" %>
      <% end %>
      <% if local_assigns[:show] && logged_in? %>
        <%= link_to "New Comment", new_article_comment_path(article), class: "card-footer-item" %>
      <% end %>
      <% if logged_in? && valid_user?(article.user) %>
        <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?" }, class: "card-footer-item" %>
      <% end %>
    </footer>
  </div>
</div>

app/views/articles/_form.html.erb
<% if article.errors.any? %>
  <div class="column is-6 is-offset-3">
    <article class="message is-danger">
      <div class="message-body">
        <p><%= pluralize(article.errors.count, "error") %>prohibited this article from being saved:</p>
        <br>
        <p><% article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %></p>
      </div>
    </article>
  </div>
<% end %>
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1><%= heading %></h1>
      </div>
    </div>
    <div class="column is-6 is-offset-3">
      <%= form_with model: article, local: true do |form| %>
        <div class="field">
          <%= form.label :title, class: "label" %>
          <div class="control">
            <%= form.text_field :title, class: "input", placeholder: "Title" %>
          </div>
        </div>
        <div class="field">
          <%= form.label :body, class: "label" %>
          <div class="control">
            <%= form.text_area :body, class: "textarea", placeholder: 'Your body' %>
          </div>
        </div>
        <div class="field is-grouped">
          <div class="control">
            <%= form.submit "Submit", class: "button is-link" %>
          </div>
          <div class="control">
            <%= link_to "Cancel", root_path, class: "button is-light" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<%= render 'form',
article: @article,
submit: 'Update Article',
cancel_path: article_path(@article),
heading: 'Edit Article' %>

app/views/articles/index.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1>Articles</h1>
      </div>
    </div>
  </div>
</div>
<% @articles.each do |article| %>
  <%= render article %>
<% end %>

<%# <div class="card text-center">
  <div class="card-header">
    <ul class="nav nav-tabs card-header-tabs">
      <li class="nav-item">
        <a class="nav-link active" href="#">Active</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
  </div>
  <div class="card-body">
    <h5 class="card-title">Special title treatment</h5>
    <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
<%= image_tag 'cars/unnamed.jpg' %> %>

app/views/articles/new.html.erb
<%= render 'form',
article: @article,
submit: 'Save Article',
cancel_path: root_path,
heading: 'New Article' %>

app/views/articles/show.html.erb
<%= render @article, show: true %>
<% @article.comments.each do |comment| %>
  <div class="column is-6 is-offset-3">
    <article class="media">
      <div class="media-content">
        <div class="content">
          <p><strong><%= comment.user.name %></strong> <small><%=time_ago_in_words(comment.created_at) %> ago</small>
            <br>
            <%= comment.body %>
          </p>
        </div>
        <nav class="level is-mobile">
          <% if valid_user?(comment.user) %>
            <div class="level-left">
              <nav class="level is-mobile">
                <div class="level-left">
                  <%= link_to edit_comment_path(comment), class: "level-item" do %>
                    <span class="icon is-small"><i class="fas fa-edit"></i></span>
                  <% end %>
                  <%= link_to comment_path(comment), method: :delete , class: "level-item", data: { confirm: "Are you sure you want to delete this comment?" } do %>
                    <span class="icon is-small"><i class="fas fa-trash-alt"></i></span>
                  <% end %>
                </div>
              </nav>
            </div>
          <% end %>
        </nav>
      </div>
    </article>
  </div>
<% end %>

app/views/comments/_comment.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <article class="media">
        <div class="media-content">
          <div class="content">
            <p>
              <strong><%=comment.commenter%></strong> <small>@johnsmith</small> <small>31m</small>
              <br>
              <%=comment.body%>
            </p>
          </div>
          <nav class="level is-mobile">
            <div class="level-left">
              <a class="level-item">
                <span class="icon is-small"><i class="fas fa-reply"></i></span>
              </a>
              <a class="level-item">
                <span class="icon is-small"><i class="fas fa-retweet"></i></span>
              </a>
              <a class="level-item">
                <span class="icon is-small"><i class="fas fa-heart"></i></span>
              </a>
            </div>
          </nav>
        </div>
      </article>
    </div>
  </div>
</div>

app/views/comments/edit.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1>Edit <%= @article.title %>'s comment</h1>
      </div>
    </div>
    <% if @comment.errors.any? %>
      <div class="column is-6 is-offset-3">
        <article class="message is-danger">
          <div class="message-body">
            <p><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</p>
            <br>
            <p>
              <% @comment.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </p>
          </div>
        </article>
      </div>
    <% end %>
    <div class="column is-6 is-offset-3">
      <article class="media">
        <div class="media-content">
          <%= form_with model: @comment, local: true do |form| %>
            <h1><%= current_user.name %>'s comment </h1>
            <div class="field">
              <p class="control">
                <%= form.text_area :body, class: "textarea", placeholder: "Add a comment..." %>
              </p>
            </div>
            <nav class="level">
              <div class="level-left">
              </div>
              <div class="level-right">
                <div class="level-item">
                  <%= form.submit "Update", class: 'button is-info' %>
                </div>
                <div class="level-item">
                  <%= link_to "Cancel", article_path(@article), class: 'button is-light'%>
                </div>
              </div>
            </nav>
          <% end %>
        </div>
      </article>
    </div>
  </div>
</div>

app/views/comments/new.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1><%= @article.title %> - New Comment</h1>
      </div>
    </div>
    <% if @comment.errors.any? %>
      <div class="column is-6 is-offset-3">
        <article class="message is-danger">
          <div class="message-body">
            <p><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</p>
            <br>
            <p>
              <% @comment.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </p>
          </div>
        </article>
      </div>
    <% end %>
    <div class="column is-6 is-offset-3">
      <article class="media">
        <div class="media-content">
          <%= form_with model: [@article, @comment], local: true do |form| %>
            <h1><%= current_user.name %>'s comment </h1>
            <div class="field">
              <p class="control">
                <%= form.text_area :body, class: "textarea", placeholder: "Add a comment..." %>
              </p>
            </div>
            <nav class="level">
              <div class="level-left">
              </div>
              <div class="level-right">
                <div class="level-item">
                  <%= form.submit "Save", class: 'button is-info' %>
                </div>
                <div class="level-item">
                  <%= link_to "Cancel", article_path(@article), class: 'button is-light'%>
                </div>
              </div>
            </nav>
          <% end %>
        </div>
      </article>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <section class="section">
      <%= render 'shared/nav_bar'%>
      <%= render 'shared/flash'%>
      <%= yield %>
    </section>
  </body>
</html>

app/views/shared/_flash.html.erb
<div class="container">
  <div class="columns is-multiline">
    <% flash.each do |name, msg| -%>
      <div class="column is-8 is-offset-2">
        <div class="notification has-text-centered is-<%= name %>">
          <%= msg %>
        </div>
      </div>
    <% end -%>
  </div>
</div>

app/views/shared/_nav_bar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to "My Blog", root_path, class: "navbar-item is-size-1"%>
    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if logged_in? %>
            <%= link_to "New Article", new_article_path, class: "button is-primary has-text-weight-bold"%>
            <%= link_to "Log Out", logout_path, method: :delete, class: "button is-primary has-text-weight-bold"%>
          <% else %>
            <%= link_to "Log In", login_path, class: "button is-primary has-text-weight-bold"%>
            <%= link_to "Sign Up", users_signup_path, class: "button is-primary has-text-weight-bold"%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <article class="message is-danger">
        <div class="message-body">
          <p><%= pluralize(@user.errors.count, "error") %>prohibited this article from being saved:</p>
          <br>
          <p><% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %></p>
        </div>
      </article>
    </div>
  </div>
<% end %>
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1>New User</h1>
      </div>
    </div>
    <div class="column is-6 is-offset-3">
      <%= form_with model: @user, local: true do |form| %>
        <div class="field">
          <%= form.label :name, class: "label" %>
          <div class="control">
            <%= form.text_field :name, class: "input", placeholder: "Your name" %>
          </div>
        </div>
        <div class="field">
          <%= form.label :email, class: "label" %>
          <div class="control">
            <%= form.email_field :email, class: "input", placeholder: 'Your email' %>
          </div>
        </div>
        <div class="field">
          <%= form.label :password, class: "label" %>
          <div class="control">
            <%= form.password_field :password, class: "input", placeholder: 'Your password' %>
          </div>
        </div>
        <div class="field">
          <%= form.label :password_confirmation, class: "label" %>
          <div class="control">
            <%= form.password_field :password_confirmation, class: "input", placeholder: 'Confirm password' %>
          </div>
        </div>
        <div class="field is-grouped">
          <div class="control">
            <%= form.submit "Submit", class: "button is-link" %>
          </div>
          <div class="control">
            <%= link_to "Cancel", root_path, class: "button is-light" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h3><%= @user.name %></h3>
        <p> <%= @user.email %> </p>
      </div>
    </div>
  </div>
</div>